name:                ZipSH
version:             0.1.0.0
github:              "Innf107/ZipSH"
license:             BSD3
author:              "Prophet"
maintainer:          "innf107@gmail.com"
copyright:           "2020 Prophet"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Innf107/ZipSH#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- bytestring
- containers
- mtl
- split
- utf8-string
- process
- ansi-escape-codes
- transformers
- exceptions
- filepath
- haskeline
- text
- time
- case-insensitive
- cereal
- digest
- conduit
- conduit-extra
- resourcet
- dlist
- monad-control
- transformers-base
- extra

library:
  source-dirs:
  - src

executables:
  zipsh:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ZipSH

tests:
  ZipSH-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ZipSH
